### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by L2jhorus** [NL0bP/Archeage-Server-emulator#14]
Hi mates, Im learning C#, and I have a forum in my webhosting in banahosting.
I wanna ask if you guys want a place in my forum so we can create guides, save research info, etc.

If you want, please let me know. And srry for create an issue to write this.

**Comment by JeyFrey** [comment]
Hey, thanks for you offer.
It would be cool to reach more people, so sure you can go ahead.

Do you mind joining our Discord on https://discord.gg/vn8E8E6 ? I guess you could have a talk with the more experienced guys there (basically not me) about what you could do there and stuff like that.
