### ISSUE TITLE
Undefined packets

### ISSUE THREAD

**Issue by JeyFrey** [NL0bP/Archeage-Server-emulator#5]
Just quoting Rain0Ash here, as its besser to have it as a new issue:
"It would be nice if all information about undefined packets were displayed (and save optionaly). Unfortunately, C# I can only read, but not write. "

**Comment by NL0bP** [comment]
I'm looking packages using wp669f specially made for ArcheAge. Included are two scripts: AA_parse2-decrypt.fsc and AA_parse2-without_decript.fsc . I usually use the second to see the source packages. The first script helps you to look at decoded (short packets) server packets DD05.
[WP669F-AA.ZIP](https://github.com/NL0bP/Archeage-Server-emulator/files/2284099/WP669F-AA.ZIP)

**Comment by Rain0Ash** [comment]
How to use it then? 😄

**Comment by NL0bP** [comment]
[Смотрю пакеты](http://prntscr.com/ki6h19)
[Копирую в код](http://prntscr.com/ki6he7)
