### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by NL0bP** [NL0bP/Archeage-Server-emulator#6]
Reconnect not work

**Comment by Yanlong-LI** [comment]
这个问题我有注意到，并解决了。

**Comment by JeyFrey** [comment]
Just adding a Google translation here:

English: "I have noticed this problem and solved it."

Russian: "Я заметил эту проблему и решил ее."

**Comment by NL0bP** [comment]
@Yanlong-LI, where is the error can you tell?
Chinese: 哪里是错误你能告诉我吗？

**Comment by Yanlong-LI** [comment]
public static byte m_NumPck = 0

这个属性应当每个网络连接独自使用，而非所有网络连接共用。

你可以看

https://github.com/NL0bP/Archeage-Server-emulator/pull/12/commits/24c7d13aa463f31dfea76cfe630094252cdccea0

**Comment by Yanlong-LI** [comment]
MY Code:

in file NetPacket.cs

private static byte m_NumPck ;  //глобальный подсчет пакетов DD05
public static byte NumPck { get => m_NumPck; set => m_NumPck = value; }



in file  ClientConnection.cs

public override void SendAsync(NetPacket packet)
        {
            packet.IsArcheAgePacket = true;
            NetPacket.NumPck = m_NumPck;
            base.SendAsync(packet);
            m_NumPck =  NetPacket.NumPck;
        }

**Comment by NL0bP** [comment]
Fix reconnect bug. Thanks Yanlong-LI
