### ISSUE TITLE
Packet_CharList

### ISSUE THREAD

**Issue by sxeroot** [NL0bP/Archeage-Server-emulator#9]
was coding the gameserver to read characters from the database but i hit a small snag i narrowed it down to this piece of code 
```
///last 1
            ///01
            ns.Write((byte)0x01);
            ///count 1
            ///02
            ns.Write((byte)0x02);
```
thats essentialy in the start of the file before the hardcoded characters.

so far i figured the second byte written corresponds to how many characters there are in the account as if i didnt have 2 characters in the database the server would hang so after testing with 2 chars all fine however when i changed the value of the byte for 1 char 0x01 while it would work, by having only 1 character in database, the rest of the character slots would become grayed out.

also the question is what is the first byte thats being written there just sais "last" does that mean the last logged in character didnt have time to test it out as i had to leave so im dropping these questions here if anyone could answer them.

**Comment by NL0bP** [comment]
//last (1 byte)
Specifies which character's number in the list came last.

**Comment by NL0bP** [comment]
//count (1 byte)
The number of heroes on the account. If 0, then the further description of a package isn't necessary. If 1, then there is a description about one hero.
